hl.on("hyprland.start", function()
  hl.exec_cmd("uwsm app -t service -- waybar")
  hl.exec_cmd("uwsm app -t service -- mako")
  hl.exec_cmd("uwsm app -t service -- hyprpaper")
  hl.exec_cmd("uwsm app -t service -- hypridle")
  hl.exec_cmd("uwsm app -t service -- /usr/libexec/lxqt-policykit-agent")
  hl.exec_cmd("uwsm app -t service -- wl-paste --type text --watch cliphist store")
  hl.exec_cmd("uwsm app -t service -- wl-paste --type image --watch cliphist store")
end)
