splash = false
ipc = true

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/assets/wallpaper.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/.config/hypr/assets/wallpaper.png
    fit_mode = cover
}
